---
- name: "apt update && apt upgrade"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  
- name: Install openjdk
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
  become: yes