---
- name: "apt update && apt upgrade"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Restart tomcat
  service:
    name: tomcat
    state: restarted
  become: yes

- name: Install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: yes

- name: Install  npm
  apt:
    name: npm
    state: present
    update_cache: yes
  become: yes

- name: npm install
  shell: npm install
  args:
    chdir: /home/vagrant/front/

- name: npm run start
  shell: (npm run start&)
  args:
    chdir: /home/vagrant/front/

#- name: Open mysql
#  shell: mysql -h "{{ db_ip }}" -u "{{ db_admin_username }}" --password="{{ db_admin_password }}"

- name: Restart tomcat
  service:
    name: tomcat
    state: restarted
  become: yes